fake_switches/telnet/__init__.py, fake_switches/telnet/stateful_telnet.py, fake_switches/telnet_service.py, tests/util/protocol_util.py
It was impossible (or very hard) to make the StatefulTelnetProtocol react to a single character and that was needed for the upcoming fake DELL support.
The new class implements Telnet directly and handles data on a key basis, stating that the server will echo character (self.will(ECHO)) and will not wait for an "enter" (or "go-ahead") to act by supressing go-ahead (self.will(SGA))
Inheritors of the class can change the self.handler to change the state
=> New stateful telnet base class that react to keys

.gitignore, fake_switches/dell/command_processor/config_interface.py, fake_switches/dell/command_processor/enabled.py, fake_switches/switch_configuration.py, tests/dell/test_configure_interface.py
2 new spanning-tree interface commands:
- spanning-tree disable
- spanning-tree portfast
4 new lldp interface commands:
- lldp transmit
- lldp receive
- lldp med transmit-tlv capabilities
- lldp med transmit-tlv network-policy
=> Add spanning-tree and lldp support on Dell

fake_switches/dell10g/command_processor/enabled.py, tests/dell10g/test_configure_interface.py
Also proposed a new way for test case sharing class definition, this way the base SSH class can be run and debugged only 1 test at a time
=> Dell10g uses double quotes in interface description names

fake_switches/cisco/command_processor/enabled.py, tests/cisco/test_cisco_auto_enabled_switch.py, tests/cisco/test_cisco_switch_protocol.py
Returns the list of port channels and members as follow:
```
cisco.switch#show etherchannel summary 
Flags:  D - down        P - bundled in port-channel
I - stand-alone s - suspended
H - Hot-standby (LACP only)
R - Layer3      S - Layer2
U - in use      f - failed to allocate aggregator
M - not in use, minimum links not met
u - unsuitable for bundling
w - waiting to be aggregated
d - default port
Number of channel-groups in use: 1
Number of aggregators:           1
Group  Port-channel  Protocol    Ports
------+-------------+-----------+-----------------------------------------------
1      Po1(SU)         LACP      Gi1/0/1(P)  Gi1/0/2(P)  
cisco.switch#
```
=> Support show etherchannel summary on cisco.

fake_switches/cisco/command_processor/enabled.py, tests/cisco/test_cisco_switch_protocol.py
Only the last digit of the channel-group number was displayed, now the number is entirely displayed.
Before:
```
interface Port-channel20
end
interface GigabitEthernet 1/0/1
channel-group 0 mode active
end
```
After:
```
interface Port-channel20
end
interface GigabitEthernet 1/0/1
channel-group 20 mode active
end
```
=> Fix display of interface channel-group on cisco.

tests/util/protocol_util.py
Prevents "out of pty devices" errors while running the tests.
Traceback:
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pty.py", line 29, in openpty
master_fd, slave_name = _open_terminal()
File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pty.py", line 70, in _open_terminal
raise os.error, 'out of pty devices'
OSError: out of pty devices
=> Disconnect by closing pexpect sessions

fake_switches/ssh_service.py
This way paramiko users won't see the SSHDemoAvatar instance has no attribute 'eofReceived' exception
=> Completed conchinterfaces.ISession implementation

fake_switches/brocade/command_processor/enabled.py, tests/brocade/test_brocade_switch_protocol.py
Ensure that the CLI answers Error - invalid interface 1/25 when calling get_interface on an unexisting interface.
Was crashing before, ports = [None]
=> get_interface with non-existing interface.

fake_switches/dell/command_processor/enabled.py, tests/dell/test_enabled.py
Supports vlan with multiple line for ports.
Supports interface using more than one letter (2/xg1).
Supports sequenced interface 1/g1-1/g2
=> Add ports support to dell show vlan {id}

fake_switches/juniper/juniper_netconf_datastore.py, fake_switches/juniper_qfx_copper/juniper_qfx_copper_netconf_datastore.py, fake_switches/netconf/__init__.py, fake_switches/netconf/netconf_protocol.py, setup.cfg, tests/juniper/juniper_base_protocol_test.py, tests/juniper_qfx_copper/juniper_qfx_copper_protocol_test.py, tests/netconf/netconf_protocol_test.py
Removing the last trunk member of a trunk interface results
in an error at commit time.
=> [juniper] Removing last trunk member errors out

tests/juniper/juniper_base_protocol_test.py, tests/juniper/juniper_base_protocol_with_commit_delay_test.py, tests/juniper_qfx_copper/juniper_qfx_copper_protocol_test.py
This was used when one test would inherit from the other, now that it doesn't no need to have this capability
=> Removed the overridable member from the juniper test

fake_switches/juniper/juniper_netconf_datastore.py, tests/juniper/juniper_base_protocol_test.py
Since the trunk vlans list was created in the candidate and copied (by reference) in the running the same instance of the list was modified on further edits therefore changing the running by the candidate
Fixes #44
=> Fixed the trunk vlan members discarding

requirements.txt
The new version is incompatible with fake-switches.
=> Force Twisted version.

fake_switches/juniper/juniper_netconf_datastore.py, fake_switches/juniper_qfx_copper/juniper_qfx_copper_netconf_datastore.py, fake_switches/netconf/__init__.py, tests/juniper/juniper_base_protocol_test.py, tests/juniper_qfx_copper/juniper_qfx_copper_protocol_test.py
both qfx and ex raises device value outside instead of Port value outside.
The ranges also varies according to the switch. Both range starts at 0.
=> Add aggregated interface on fake-switches should react as the switch does

fake_switches/juniper/juniper_netconf_datastore.py, tests/juniper/__init__.py, tests/juniper/juniper_base_protocol_test.py, tests/juniper_qfx_copper/juniper_qfx_copper_protocol_test.py
Empty interfaces in juniper are not shown through the interface.
Fake-switch now replicate this behaviour.
=> Changed the way we simulate empty interfaces in juniper

setup.cfg
This will add the README, the license and the url in the PKGINFO,
this way, Pypi will be able to get the description of our project.
=> Improve PKG-INFO for pypi description

fake_switches/brocade/command_processor/__init__.py, tests/brocade/test_brocade_switch_protocol.py
Brocade switches validates port properly in most cases. It would not
behave properly if the port was incorrectly named something99
(missing slash in port info)
=> Added a test case and support for another type of invalid port

fake_switches/juniper/juniper_netconf_datastore.py, tests/juniper/__init__.py, tests/juniper/juniper_base_protocol_test.py, tests/juniper_qfx_copper/juniper_qfx_copper_protocol_test.py
To be more consistent with the switch, when nothing is returned
the configuration tag should be empty instead of having empty
interfaces, vlans and protocols.
To ensure the base no-configuration test always work, a tear down
check that all configuration has been reset has been added
This raised an issue with the LLDP not cleared properly and has
been addressed
Fixes #65
=> Stop returning empty configurations parts

fake_switches/juniper/juniper_core.py, fake_switches/juniper/juniper_netconf_datastore.py, fake_switches/juniper_qfx_copper/juniper_qfx_copper_core.py, fake_switches/switch_configuration.py, tests/juniper/juniper_base_protocol_test.py, tests/util/global_reactor.py
The problem rose when trying to get rid of the rstp protocols
xml node without an existing interface, the interface will now
always exist as they should always have to mimic the real
juniper.
You can assert this behavior by the get-interface-information terse
and see all the aggregated ports in there
=> Add default AE ports to juniper

fake_switches/juniper/juniper_netconf_datastore.py, fake_switches/juniper_qfx_copper/juniper_qfx_copper_netconf_datastore.py, tests/juniper/juniper_base_protocol_test.py, tests/juniper_qfx_copper/juniper_qfx_copper_protocol_test.py
The data returned contains new lines before and after
every value of the xml tree
This behavior has been verified on junos 12 and 14
=> Return the correct data with get information command

test-requirements.txt
This will ensure that we use a tagged version and not the current master
that might be broken.
=> Use latest tagged ncclient

fake_switches/juniper/juniper_netconf_datastore.py, fake_switches/netconf/__init__.py, fake_switches/netconf/netconf_protocol.py, tests/juniper/juniper_base_protocol_test.py, tests/juniper_qfx_copper/juniper_qfx_copper_protocol_test.py
To more precisely exert the behavior of the real switch
the auto-negotiation on aggregated ports have been removed
a support for auto-negotiation and no-auto-negotiation
has been added to interface along with their delete
A support for multiple errors was introduced because that's
how the switch behave when given the 2 options at the same
time
=> Support full auto-negotiation flags

fake_switches/netconf/__init__.py, tests/juniper/juniper_base_protocol_test.py, tests/juniper_qfx_copper/juniper_qfx_copper_protocol_test.py
They should all be starting with a lower casing
=> Fix the case of error messages

fake_switches/dell/command_processor/config_interface.py, tests/dell/test_configure_interface.py
This allows to reset the portmode of the switch and associated
attributes without knowing the current switchport state.
=> Add no switchport mode to dell switch

fake_switches/ssh_service.py
byte-compiling /usr/local/lib/python3.5/site-packages/fake_switches/ssh_service.py to ssh_service.cpython-35.pyc
File "/usr/local/lib/python3.5/site-packages/fake_switches/ssh_service.py", line 71
raise Exception, "No supported interfaces found."
^
SyntaxError: invalid syntax
=> Fix python 3.5 incompatibilities

Dockerfile, README.md, requirements.txt
Currently, we depend on lxml for the Juniper simulator. This requirement
wasnt in requirements.txt.
This commit adds it, switches the Docker base image to the Alpine one
and fixes the README instructions for running the container.
=> Add missing lxml dependency in container

requirements.txt
Twisted 15.5.0 seemed to have problems with stability and some SSH
negociation errors were happening often, The new version 16 seems to not
have this problems. This will get rid of some false-negatives.
=> Bump twisted version to 16

requirements.txt
There is no need for a separate dependency, twisted[conch] contains all
the requirements for using ssl with twisted.
=> Use twisted to get cryptography

fake_switches/cmd/main.py, fake_switches/ssh_service.py, tests/cmd/test_main.py, tests/util/global_reactor.py
When using main(), the password was not encoded causing a type error in Python3
=> Fix password encoding for python 3 in main()

fake_switches/cisco/command_processor/config_interface.py, fake_switches/cisco/command_processor/enabled.py, fake_switches/switch_configuration.py, tests/cisco/test_cisco_switch_protocol.py
Version 1 is default.
Version 2 is the only other one supported at the
moment and is the only one to appear in the running-config
=> Add support for cisco's standby version command

fake_switches/juniper/juniper_netconf_datastore.py, fake_switches/juniper_mx/juniper_mx_netconf_datastore.py, tests/juniper_mx/juniper_mx_protocol_test.py
Upon committing the add_ip and remove_ip are used to carry the IP
information to whoever is listening ;)
We should definitely move to a event system, this configuration
subclassing makes it hard to keep a good contract.
=> Add ip removal support for interface vlans

fake_switches/juniper_mx/juniper_mx_netconf_datastore.py, fake_switches/switch_configuration.py, tests/juniper_mx/juniper_mx_protocol_test.py
Supports adding a VIP and a priority, more fields to come
Since VRRPs can technically be attached to anything, it was easier
for rendering to keep a record of which IP it belongs to.
Seemed easier than to try and reverse engineer from the vip to which
subnet it would belong.
=> Add basic vrrp groups support for juniper mx

fake_switches/juniper_mx/juniper_mx_netconf_datastore.py, tests/juniper_mx/juniper_mx_protocol_test.py
Avoids having the same ip inserted in 2 different places
=> Duplicate IP catch on JuniperMX

fake_switches/cisco/command_processor/enabled.py, fake_switches/cisco6500/cisco_core.py, fake_switches/switch_configuration.py, tests/cisco6500/test_cisco6500_switch_interface.py
This is the implementation of "ntp disable" and "no ntp disable" for
the Cisco 6500
=> ntp disable support on Cisco 6500

README.md, fake_switches/cmd/main.py, fake_switches/transports/__init__.py, fake_switches/transports/base_transport.py, fake_switches/transports/ssh_service.py, fake_switches/transports/telnet_service.py, tests/util/global_reactor.py
SwitchSshService and SwitchTelnetService are now deprecated in favor of
transports.SwitchSshService and transports.SwitchTelnetService that are
based on a standard transport super class.
=> Standardizing the transport instantiation

constraints.txt, fake_switches/arista/arista_core.py, fake_switches/arista/command_processor/__init__.py, fake_switches/arista/command_processor/config.py, fake_switches/arista/command_processor/config_vlan.py, fake_switches/arista/command_processor/default.py, fake_switches/arista/command_processor/enabled.py, fake_switches/arista/command_processor/terminal_display.py, fake_switches/arista/eapi.py, fake_switches/command_processing/shell_session.py, fake_switches/transports/http_service.py, test-constraints.txt, test-requirements.txt, tests/arista/test_arista_rest_api.py, tests/arista/test_arista_running_config.py, tests/arista/test_arista_switch_protocol.py, tests/util/global_reactor.py, tox.ini
The errors can now display partial result which are currently ignored
by the terminal display.
The show vlan and config vlan share the same validation routine so it
was pushed to the common parent.
=> Add the support for errors in json format

fake_switches/arista/eapi.py, tests/arista/test_arista_rest_api.py
A command with an empty response should return an empty json object
=> Support empty reponses

fake_switches/transports/__init__.py, fake_switches/transports/http_service.py, fake_switches/transports/ssh_service.py, fake_switches/transports/telnet_service.py, tests/test_transports.py
This will increase the compatibility between transports services and
deprecated ssh_service and telnet_service.
80 for HTTP
22 for SSH
23 for Telnet
=> Add default ports for transports services

fake_switches/arista/arista_core.py, fake_switches/arista/command_processor/__init__.py, fake_switches/arista/command_processor/default.py, fake_switches/arista/command_processor/terminal_display.py, fake_switches/arista/eapi.py
Having one for each processor was indeed simplifying how to pass the
output channel (the processor itself) on instantiation but it causes a
problem in the EAPI since that service holds a reference to the base
processor only and the base processor is the one dispatching down its
tree so it's hard to know which processor processed the command to get
that processor's display to get the output object.
Having a unique display and passing the output channel on each call will
solve this as we don't care who processed it.
We cannot simply pass the terminal controller to the display since there
is a piping mechanism in the .write that would need to be copied. A
refactor could turn that into a mixin, or the terminal controller could
controller the piping.
=> Use a unique display object

fake_switches/arista/command_processor/config_interface.py, fake_switches/arista/command_processor/enabled.py, fake_switches/switch_configuration.py, tests/arista/test_arista_load_interval.py
This is used to gather statistics on the interface on arista switches.
=> Add load-interval support on interface vlan

fake_switches/arista/command_processor/config_interface.py, fake_switches/arista/command_processor/enabled.py, fake_switches/switch_configuration.py, tests/arista/test_arista_mpls_ip.py
MPLS is a networking process that replaces complete network addresses with
short path labels for directing data packets to network nodes.
=> Add mpls ip support on interface vlan
